---
title: "Model Building"
output: html_document
date: "2024-10-27"
---

```{r}
library(dplyr)
library(stringr)
#install.packages("remotes")
library(remotes)
#remotes::install_github("kuriwaki/ccesMRPprep")
#library(ccesMRPprep)
#install.packages("data.table")
library(data.table)
library(tidyr)
```

```{r}
#loading data
final_data <- read.csv("/Users/liam/Downloads/courses/PLSC_204/ISPS Election Prediction/full_district_data_v2.csv")

```

```{r}
#explore data
colnames(final_data)

#adding a col called rep_pres_votes
final_data$rep_pres_votes_now <- final_data$rep_pct_pres_now * final_data$presvotes_total_now
final_data$rep_pres_votes_last <- final_data$rep_pct_pres_last * final_data$presvotes_total_last
  
```

```{r}
#model to predict rep_pres_votes
final_data_16_to_20 <- subset(final_data, year %in% c(2016,2020))
#narrowing to elections in which trump has competed (and for which we have past vote info)

pres_lm1 = lm(rep_pres_votes_now ~ relative_partisanship_CPVI + rep_pres_votes_last + pct_male + pct_senior, data = final_data_16_to_20)

summary(pres_lm1)

```

```{r}
#final data but only for 2024 and with cd, year, state_ab

pred_data_2024 <- subset(final_data, year == 2024)


#use model to predict rep_pres_votes for 2024

pred_data_2024$rep_pres_votes_pred <- predict(pres_lm1, newdata = pred_data_2024)

```

```{r}

#now need to predict turnout, presvotes_total_now

pres_lm2 = lm(presvotes_total_now ~ relative_partisanship_CPVI + rep_pres_votes_last + pct_black + pct_latino + pct_senior, data = final_data_16_to_20)

summary(pres_lm2)

```

```{r}
#adding presvotes_total_now predictions to pred_data_2024

pred_data_2024$presvotes_total_pred <- predict(pres_lm2, newdata = pred_data_2024)

```

```{r}


#sum up rep_pres_votes_pred and rep_pres_votes_last for each state

PQ1 <- pred_data_2024 %>%
  group_by(state_ab) %>%
  summarise(rep_pres_votes_pred = sum(rep_pres_votes_pred), presvotes_total_pred = sum(presvotes_total_pred), pct_rep_pres_pred = sum(rep_pres_votes_pred) / sum(presvotes_total_pred))



```  
          
```{r}


```











